name: scipy_dev

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python ==3.9
  - pip

  # Dependencies
  - pandas
  - numpy
  - scipy
  - jupyterlab
  - ipython
  - seaborn
  - jax
  - estimagic

  # Algorithms
  - nlopt
  - pygmo

  # Misc Start
  - setuptools_scm
  - toml
  - pytask >=0.2.3
  - black
  - nb_black
  - pre-commit
  - pdbpp
  - pytest
  - pytest-cov
  - pytest-xdist
  - tox-conda
  - conda-lock
  # Misc End

  - pip:
    - black
    - blackcellmagic
    - kaleido

    # Pip Algorithms
    - jaxopt
    - Py-BOBYQA
    - DFO-LS
    - fides==0.7.4
