name: scipy_dev

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python ==3.9
  - pip
  - setuptools_scm
  - toml

  # Reproducibility
  - conda-lock

  # Package dependencies
  - pytask >=0.2.3
  - pandas
  - numpy
  - jupyterlab
  - seaborn

  # Misc
  - black
  - nb_black
  - ipython
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-xdist
  - tox-conda

  - pip:
    - black
    - blackcellmagic
    - pre-commit
